Repository wallabag/wallabag, pull requests merged in 2018-11, with the labels that each got.

#3764 Fix documentation wording for matches/notmatches tagging rules
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
Labels: Ready for review, Translations

#3772 Update translation when marking as read
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
Labels: Translations

#3774 Card no preview replaced by wallabag logo
  app/Resources/static/themes/material/css/cards.scss
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
  web/wallassets/baggy.js
  web/wallassets/manifest.json
  web/wallassets/material.css
  web/wallassets/material.js
  web/wallassets/public.js
Labels: UI

#3775 Prepare 2.3.4 release
  .travis.yml
  CHANGELOG.md
  app/config/wallabag.yml
  composer.json
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
Labels: Ready for review

#3778 Jump to 2.3.5-dev and update release process
  RELEASE_PROCESS.md
  app/config/wallabag.yml
  scripts/release.sh
Labels: Ready for review

#3765 Remove preview picture from single entry view page for #1875
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Labels: Ready for review

#3782 material: fix missing thumbnail on list view
  app/Resources/static/themes/material/css/cards.scss
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
Labels: Ready for review, UI

#3783 material: decrease size of tags on list view
  app/Resources/static/themes/material/css/cards.scss
Labels: Ready for review, UI

#3758 Dropping PHP < 7.1
  .travis.yml
  .zappr.yaml
  COPYING.md
  README.md
  app/AppKernel.php
  app/DoctrineMigrations/Version20180405182455.php
  app/DoctrineMigrations/Version20181128203230.php
  app/autoload.php
  app/config/config.yml
  app/config/config_test.yml
  app/config/parameters.yml.dist
  app/config/parameters_test.yml
  app/config/services_test.yml
  app/config/tests/parameters_test.mysql.yml
  app/config/tests/parameters_test.pgsql.yml
  app/config/tests/parameters_test.sqlite.yml
  bin/console
  composer.json
  phpunit.xml.dist
  src/Wallabag/AnnotationBundle/DataFixtures/AnnotationFixtures.php
  src/Wallabag/ApiBundle/Entity/AccessToken.php
  src/Wallabag/ApiBundle/Entity/AuthCode.php
  src/Wallabag/ApiBundle/Entity/RefreshToken.php
  src/Wallabag/CoreBundle/DataFixtures/ConfigFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/EntryFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/SettingFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/SiteCredentialFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/TagFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/TaggingRuleFixtures.php
  src/Wallabag/CoreBundle/Doctrine/DBAL/Driver/CustomPostgreSQLDriver.php
  src/Wallabag/CoreBundle/Doctrine/DBAL/Schema/CustomPostgreSqlSchemaManager.php
  src/Wallabag/CoreBundle/Doctrine/WallabagMigration.php
  src/Wallabag/CoreBundle/Entity/TaggingRule.php
  src/Wallabag/UserBundle/DataFixtures/UserFixtures.php
  tests/Wallabag/AnnotationBundle/Controller/AnnotationControllerTest.php
  tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
  tests/Wallabag/ApiBundle/WallabagApiTestCase.php
  tests/Wallabag/CoreBundle/Command/InstallCommandTest.php
  tests/Wallabag/ImportBundle/Command/ImportCommandTest.php
  web/app.php
  web/app_dev.php
Labels: Ready for review
