Repository wallabag/wallabag, pull requests merged in 2018-12, with the labels that each got.

#3799 Update messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
Labels: Translations

#3781 build: upgrade yarn dependencies, update prod assets
  web/wallassets/baggy.js
  web/wallassets/manifest.json
  web/wallassets/material.css
  web/wallassets/material.js
  web/wallassets/public.js
  yarn.lock
Labels: Ready for review, UI

#3810 No more dev for guzzle-site-authenticator
  composer.json
Labels: Ready for review

#3812 Prepare 2.3.5 release
  CHANGELOG.md
  RELEASE_PROCESS.md
  app/config/wallabag.yml
Labels: Ready for review

#3814 Jump to 2.3.6-dev and update release process
  RELEASE_PROCESS.md
  app/config/wallabag.yml
  scripts/release.sh
Labels: Ready for review
