Repository wallabag/wallabag, pull requests merged in 2018-07, with the labels that each got.

#3684 Fix image downloading on null image path
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
Labels: Ready for review

#3685 Replace SO url by lemonde.fr to avoid random failing test
  tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php
  tests/Wallabag/ImportBundle/fixtures/firefox-bookmarks.json
Labels: Ready for review

#3686 Remove remaining deprecation notices
  app/config/config.yml
Labels: Ready for review

#3683 Fix mobile viewport on big iframe and video elements
  app/Resources/static/themes/_global/share.scss
  web/wallassets/public.css
Labels: UI

#3678 Propose YunoHost badge for installing
  README.md
Labels: Documentation

#3691 Autofocus the username field on the login page
  src/Wallabag/UserBundle/Resources/views/Security/login.html.twig
Labels: UI

#3692 Feature/svg logo
  app/Resources/static/themes/_global/img/logo-other_themes.png
  app/Resources/static/themes/_global/img/logo-square.png
  app/Resources/static/themes/_global/img/logo-square.svg
  app/Resources/static/themes/_global/img/logo-wallabag.svg
  app/Resources/static/themes/material/css/layout.scss
  src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Exception/error.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
  src/Wallabag/UserBundle/Resources/views/layout.html.twig
  web/wallassets/baggy.css
  web/wallassets/material.css
  web/wallassets/themes/_global/img/logo-other_themes.png
  web/wallassets/themes/_global/img/logo-square.png
  web/wallassets/themes/_global/img/logo-square.svg
  web/wallassets/themes/_global/img/logo-wallabag.svg
Labels: UI
