Repository wallabag/wallabag, pull requests merged in 2018-10, with the labels that each got.

#3731 Jump to Symfony 3.4
  app/AppKernel.php
  app/config/config.yml
  app/config/config_test.yml
  app/config/security.yml
  app/config/services.yml
  app/config/services_test.yml
  composer.json
  src/Wallabag/ApiBundle/Controller/DeveloperController.php
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Controller/ExportController.php
  src/Wallabag/CoreBundle/Controller/RssController.php
  src/Wallabag/CoreBundle/Controller/SiteCredentialController.php
  src/Wallabag/CoreBundle/Controller/StaticController.php
  src/Wallabag/CoreBundle/Controller/TagController.php
  src/Wallabag/CoreBundle/Resources/config/services.yml
  src/Wallabag/ImportBundle/Controller/BrowserController.php
  src/Wallabag/ImportBundle/Controller/ChromeController.php
  src/Wallabag/ImportBundle/Controller/FirefoxController.php
  src/Wallabag/ImportBundle/Controller/ImportController.php
  src/Wallabag/ImportBundle/Controller/InstapaperController.php
  src/Wallabag/ImportBundle/Controller/PinboardController.php
  src/Wallabag/ImportBundle/Controller/PocketController.php
  src/Wallabag/ImportBundle/Controller/ReadabilityController.php
  src/Wallabag/ImportBundle/Controller/WallabagV1Controller.php
  src/Wallabag/ImportBundle/Controller/WallabagV2Controller.php
  src/Wallabag/ImportBundle/Resources/config/services.yml
  src/Wallabag/UserBundle/Controller/ManageController.php
  tests/Wallabag/AnnotationBundle/WallabagAnnotationTestCase.php
  tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php
  tests/Wallabag/ApiBundle/WallabagApiTestCase.php
  tests/Wallabag/CoreBundle/Command/ReloadEntryCommandTest.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/CoreBundle/WallabagCoreTestCase.php
Labels: Ready for review

#3596 Add secure email
  app/config/config.yml
  app/config/parameters.yml.dist
Labels: Ready for review

#3734 Fix dockerfile php72
  docker/php/Dockerfile
Labels: Ready for review

#3743 Show tags on non-image gallery preview card
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_no_preview.html.twig
Labels: Ready for review, UI

#3216 Added possibility to change locale from login/register pages
  app/config/security.yml
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Event/Listener/UserLocaleListener.php
  src/Wallabag/UserBundle/EventListener/CreateConfigListener.php
  src/Wallabag/UserBundle/Resources/config/services.yml
  src/Wallabag/UserBundle/Resources/views/Registration/register_content.html.twig
  src/Wallabag/UserBundle/Resources/views/layout.html.twig
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
  tests/Wallabag/CoreBundle/Event/Listener/UserLocaleListenerTest.php
  tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
Labels: Ready for review

#3574 Allow to rename tags from the web interface.
  app/Resources/static/themes/_global/index.js
  app/Resources/static/themes/baggy/css/layout.scss
  app/Resources/static/themes/material/css/cards.scss
  src/Wallabag/CoreBundle/Controller/TagController.php
  src/Wallabag/CoreBundle/Form/Type/RenameTagType.php
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Tag/tags.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig
  tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
  web/wallassets/baggy.css
  web/wallassets/baggy.js
  web/wallassets/manifest.json
  web/wallassets/material.css
  web/wallassets/material.js
  web/wallassets/public.js
Labels: Ready for review

#3745 Add placeholder image to card-based gallery entries page
  app/Resources/static/themes/material/css/cards.scss
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_no_preview.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
  web/wallassets/material.css
Labels: Ready for review, UI

#3553 Swap entry url with origin url if graby provides an updated one
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
  tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
Labels: Ready for review

#3763 Add note on GitHub PR template to auto-close issues
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Improvement, Ready for review
