Repository wallabag/wallabag, pull requests merged in 2019-05, with the labels that each got.

#3942 material: add metadata to list view
  app/Resources/static/themes/material/css/cards.scss
  app/Resources/static/themes/material/css/media_queries.scss
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/Card/_content.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
Labels: Ready for review, UI

#3955 Use Imagick to keep GIF animation
  .travis.yml
  composer.json
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  tests/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilderTest.php
  tests/Wallabag/CoreBundle/ParamConverter/UsernameFeedTokenConverterTest.php
  tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
Labels: Ready for review

#3943 Enable no-referrer on img tags, enable strict-origin-when-cross-origin by default
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
  src/Wallabag/CoreBundle/Resources/views/base.html.twig
  web/wallassets/material.css
Labels: Improvement, Ready for review

#3922 Remove preview picture from share view page for #1875
  src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig
Labels: Ready for review

#3956 Cascade delete on oauth2 table when deleting a user
  app/DoctrineMigrations/Version20190510141130.php
  src/Wallabag/ApiBundle/Entity/AccessToken.php
  src/Wallabag/ApiBundle/Entity/AuthCode.php
  src/Wallabag/ApiBundle/Entity/RefreshToken.php
Labels: Ready for review

#3964 Fix Intl Locale issue
  composer.json
Labels: Ready for review

#3966 Prepare 2.3.8 release
  CHANGELOG.md
  app/config/wallabag.yml
Labels: Ready for review

#3960 api/entries: add parameter detail to exclude or include content in response
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
  tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
Labels: API, Ready for review

#3977 Force PHP version in Dockerfile
  docker/php/Dockerfile
Labels: Ready for review

#3980 Fix Instapaper import date order
  src/Wallabag/ImportBundle/Import/InstapaperImport.php
Labels: Ready for review

#3965 Preview picture: use the 1st pic retrieved if no og:image set
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
  tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
Labels: Ready for review

#3982 Fix http/https test
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
Labels: Ready for review

#3390 Use httplug and graby 2.0
  app/AppKernel.php
  app/config/config.yml
  composer.json
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  src/Wallabag/CoreBundle/Helper/HttpClientFactory.php
  src/Wallabag/CoreBundle/Resources/config/services.yml
  src/Wallabag/ImportBundle/Import/PocketImport.php
  src/Wallabag/ImportBundle/Import/WallabagV2Import.php
  src/Wallabag/ImportBundle/Resources/config/services.yml
  tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
  tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
  tests/Wallabag/ImportBundle/Import/PocketImportTest.php
Labels: Ready for review

#3944 Always hash exists url
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/CoreBundle/Command/GenerateUrlHashesCommand.php
  src/Wallabag/CoreBundle/Entity/Entry.php
  src/Wallabag/CoreBundle/Helper/UrlHasher.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
Labels: Ready for review

#3985 Keep composer.lock
  .gitignore
  RELEASE_PROCESS.md
  app/config/wallabag.yml
  composer.lock
  scripts/release.sh
Labels: Ready for review

#3986 Fix some Scrutinizer issues
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/ApiBundle/Controller/UserRestController.php
  src/Wallabag/ApiBundle/Controller/WallabagRestController.php
  src/Wallabag/CoreBundle/Entity/Entry.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
Labels: Ready for review

#3987 Drop SimplePie
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
Labels: Ready for review
