Repository wallabag/wallabag, pull requests merged in 2019-07, with the labels that each got.

#4039 Fix hardcoded `wallabag_` prefix in migrations
  app/DoctrineMigrations/Version20170511211659.php
  app/DoctrineMigrations/Version20190425115043.php
  app/DoctrineMigrations/Version20190619093534.php
Labels: Ready for review

#4050 Update deps
  composer.lock
Labels: Ready for review

#4049 Add missing tidy extension on Docker
  docker/php/Dockerfile
Labels: Ready for review

#4028 Add ability to import/export tagging rules
  .gitignore
  src/Wallabag/ApiBundle/Controller/TaggingRuleRestController.php
  src/Wallabag/ApiBundle/Resources/config/routing_rest.yml
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Entity/TaggingRule.php
  src/Wallabag/CoreBundle/Form/Type/TaggingRuleImportType.php
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
  tests/Wallabag/ApiBundle/Controller/TaggingRuleRestControllerTest.php
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
  tests/Wallabag/CoreBundle/fixtures/tagging_rules_admin.json
Labels: Missing: doc, Ready for review

#4053 Add ability to manually define the reading speed
  app/DoctrineMigrations/Version20190708122957.php
  src/Wallabag/CoreBundle/DataFixtures/ConfigFixtures.php
  src/Wallabag/CoreBundle/Form/Type/ConfigType.php
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_reading_time.html.twig
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
Labels: Ready for review

#4054 Remove PHPUnit lock
  .travis.yml
  composer.lock
  phpstan.neon
Labels: Ready for review

#4058 Copy client info to clipboard
  app/Resources/static/themes/_global/index.js
  package.json
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/common/Developer/client_parameters.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/common/Developer/index.html.twig
  tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php
  web/wallassets/baggy.js
  web/wallassets/material.js
  web/wallassets/public.js
  yarn.lock
Labels: Ready for review

#4063 Use a custom cookiejar to avoid error when the cookie is badly saved
  composer.lock
  src/Wallabag/CoreBundle/Helper/FileCookieJar.php
  src/Wallabag/CoreBundle/Resources/config/services.yml
Labels: Ready for review

#4071 Update of Occitan language
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
Labels: Translations

#4072 Test on PHP 7.4 instead of PHP 8.0 on Travis
  .travis.yml
Labels: Ready for review
