Repository wallabag/wallabag, pull requests merged in 2019-11, with the labels that each got.

#4162 Add package and PHP extension to PHP docker
  docker/php/Dockerfile
Labels: Ready for review

#4163 Increase php memory limit PHP Docker
  docker/php/Dockerfile
Labels: Ready for review

#4175 Added elCurator import
  app/config/config.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/ImportBundle/Controller/ElcuratorController.php
  src/Wallabag/ImportBundle/Import/ElcuratorImport.php
  src/Wallabag/ImportBundle/Resources/config/rabbit.yml
  src/Wallabag/ImportBundle/Resources/config/redis.yml
  src/Wallabag/ImportBundle/Resources/config/services.yml
  src/Wallabag/ImportBundle/Resources/views/Elcurator/index.html.twig
  tests/Wallabag/ImportBundle/Controller/ElcuratorControllerTest.php
  tests/Wallabag/ImportBundle/Controller/ImportControllerTest.php
  tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
  tests/Wallabag/ImportBundle/fixtures/elcurator.json
Labels: Import, Ready for review

#4150 💄 Add untagged list link to filter menu
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Labels: Ready for review

#4152 Add environment variables to control scripts/dev.sh behavior
  scripts/dev.sh
Labels: Improvement

#4151 ✨ Allow custom styles system wide
  .gitignore
  GNUmakefile
  src/Wallabag/CoreBundle/Resources/views/base.html.twig
Labels: Ready for review
