Repository wallabag/wallabag, pull requests merged in 2019-03, with the labels that each got.

#3885 Allow optional --ignore-root-warning
  scripts/install.sh
  scripts/update.sh
Labels: Ready for review

#3868 Add missing entries in craue_config_setting.
  app/DoctrineMigrations/Version20190129120000.php
Labels: Ready for review

#3893 material: fix left padding of content on medium screens
  app/Resources/static/themes/material/css/cards.scss
  app/Resources/static/themes/material/css/media_queries.scss
Labels: Ready for review, UI

#3894 material: hide creation date from card actions on specific sizes
  app/Resources/static/themes/material/css/cards.scss
  app/Resources/static/themes/material/css/media_queries.scss
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_actions.html.twig
  web/wallassets/material.css
Labels: Ready for review, UI

#3895 Prepare 2.3.7 release
  CHANGELOG.md
  app/config/wallabag.yml
Labels: Ready for review

#3897 Jump to 2.3.8-dev
  app/config/wallabag.yml
Labels: Ready for review

#3901 material: fix left padding on non-entry pages introduced by #3893
  app/Resources/static/themes/material/css/media_queries.scss
  web/wallassets/material.css
Labels: Bug, UI

#3860 Make dev/install/update script posix compatible
  scripts/dev.sh
  scripts/install.sh
  scripts/update.sh
Labels: Ready for review

#3908 epub: fix exception when articles have the same title
  src/Wallabag/CoreBundle/Helper/EntriesExport.php
Labels: Ready for review

#3909 Fix PHP warning
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
Labels: Ready for review
