Repository wallabag/wallabag, pull requests merged in 2019-01, with the labels that each got.

#3823 Fix tag API leak
  src/Wallabag/ApiBundle/Controller/TagRestController.php
  src/Wallabag/CoreBundle/DataFixtures/ORM/LoadEntryData.php
  src/Wallabag/CoreBundle/DataFixtures/ORM/LoadTagData.php
  src/Wallabag/CoreBundle/Repository/TagRepository.php
  tests/Wallabag/ApiBundle/Controller/TagRestControllerTest.php
Labels: API, Ready for review, Security

#3816 Validate imported entry to avoid error on import
  src/Wallabag/ImportBundle/Consumer/AbstractConsumer.php
  src/Wallabag/ImportBundle/Import/AbstractImport.php
  src/Wallabag/ImportBundle/Import/BrowserImport.php
  src/Wallabag/ImportBundle/Import/ChromeImport.php
  src/Wallabag/ImportBundle/Import/FirefoxImport.php
  src/Wallabag/ImportBundle/Import/InstapaperImport.php
  src/Wallabag/ImportBundle/Import/PinboardImport.php
  src/Wallabag/ImportBundle/Import/PocketImport.php
  src/Wallabag/ImportBundle/Import/ReadabilityImport.php
  src/Wallabag/ImportBundle/Import/WallabagImport.php
Labels: Ready for review

#3820 Fix incorrect reading time calculation for entries with CJK characters
  src/Wallabag/CoreBundle/Tools/Utils.php
  tests/Wallabag/CoreBundle/Tools/UtilsTest.php
  tests/Wallabag/CoreBundle/Tools/samples/README
  tests/Wallabag/CoreBundle/Tools/samples/chinese.txt
  tests/Wallabag/CoreBundle/Tools/samples/cyrillic.txt
  tests/Wallabag/CoreBundle/Tools/samples/greek.txt
  tests/Wallabag/CoreBundle/Tools/samples/japanese.txt
  tests/Wallabag/CoreBundle/Tools/samples/korean.txt
  tests/Wallabag/CoreBundle/Tools/samples/latin.txt
Labels: Improvement, Ready for review

#3833 Fix settings field inverted
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Labels: Ready for review

#3831 Cast client id to avoid PG error
  src/Wallabag/ApiBundle/Entity/Client.php
  src/Wallabag/ApiBundle/Repository/ClientRepository.php
  tests/Wallabag/ApiBundle/Controller/DeveloperControllerTest.php
Labels: Ready for review

#3826 Rework of EPUB/PDF exports
  src/Wallabag/CoreBundle/Controller/ExportController.php
  src/Wallabag/CoreBundle/Helper/EntriesExport.php
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
Labels: Improvement, Ready for review

#3835 Prepare 2.3.6 release
  CHANGELOG.md
  app/config/wallabag.yml
Labels: Ready for review

#3837 Jump to 2.3.7-dev
  app/config/wallabag.yml
Labels: Ready for review

#3845 Add a new endpoint to retrieve information from the wallabag instance
  app/config/security.yml
  src/Wallabag/ApiBundle/Controller/WallabagRestController.php
  tests/Wallabag/ApiBundle/Controller/WallabagRestControllerTest.php
Labels: API, Ready for review

#3853 Update composer.json to add php-tidy (ext-tidy)
  composer.json
Labels: Ready for review

#3861 Add dedicated email for site config issue
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Labels: Meta, Ready for review

#3859 Enable PHPStan
  .travis.yml
  app/DoctrineMigrations/Version20190117131816.php
  composer.json
  phpstan.neon
  src/Wallabag/CoreBundle/Command/InstallCommand.php
  src/Wallabag/CoreBundle/Entity/SiteCredential.php
  src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
  tests/Wallabag/AnnotationBundle/Controller/AnnotationControllerTest.php
  tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
  tests/Wallabag/CoreBundle/Controller/RssControllerTest.php
  tests/Wallabag/CoreBundle/Helper/RedirectTest.php
  tests/Wallabag/CoreBundle/ParamConverter/UsernameRssTokenConverterTest.php
  tests/Wallabag/ImportBundle/Consumer/AMQPEntryConsumerTest.php
  tests/Wallabag/ImportBundle/Consumer/RedisEntryConsumerTest.php
  tests/Wallabag/ImportBundle/Controller/ChromeControllerTest.php
  tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php
  tests/Wallabag/ImportBundle/Controller/InstapaperControllerTest.php
  tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
  tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
  tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
  tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php
  tests/Wallabag/UserBundle/Controller/ManageControllerTest.php
  tests/Wallabag/UserBundle/Mailer/AuthCodeMailerTest.php
  tests/Wallabag/UserBundle/Mailer/CountableMemorySpool.php
Labels: Ready for review

#3864 Removed hardcoded database version
  .travis.yml
  app/config/config.yml
Labels: Ready for review

#3627 Add a basic Search REST endpoint
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/ApiBundle/Controller/SearchRestController.php
  src/Wallabag/ApiBundle/Controller/WallabagRestController.php
  src/Wallabag/ApiBundle/Resources/config/routing_rest.yml
  tests/Wallabag/ApiBundle/Controller/SearchRestControllerTest.php
Labels: API, Feature, Ready for review

#3819 Fix read & starred status in Pocket import
  src/Wallabag/ImportBundle/Import/PocketImport.php
  tests/Wallabag/ImportBundle/Import/PocketImportTest.php
Labels: Ready for review

#3798 Enable OTP 2FA
  .editorconfig
  .travis.yml
  app/DoctrineMigrations/Version20181202073750.php
  app/Resources/static/themes/_global/index.js
  app/Resources/static/themes/material/index.js
  app/config/config.yml
  app/config/routing.yml
  app/config/security.yml
  composer.json
  src/Wallabag/CoreBundle/Command/ShowUserCommand.php
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Form/Type/UserInformationType.php
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/otp_app.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Config/otp_app.html.twig
  src/Wallabag/UserBundle/Controller/ManageController.php
  src/Wallabag/UserBundle/Entity/User.php
  src/Wallabag/UserBundle/Form/UserType.php
  src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php
  src/Wallabag/UserBundle/Resources/views/Authentication/form.html.twig
  src/Wallabag/UserBundle/Resources/views/Manage/edit.html.twig
  tests/Wallabag/CoreBundle/Command/ShowUserCommandTest.php
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
  tests/Wallabag/CoreBundle/Controller/SecurityControllerTest.php
  tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
  tests/Wallabag/UserBundle/Mailer/AuthCodeMailerTest.php
Labels: Ready for review
