Repository wallabag/wallabag, pull requests merged in 2019-02, with the labels that each got.

#3869 Fix broken 2 factor auth logo image
  src/Wallabag/UserBundle/Resources/views/TwoFactor/email_auth_code.html.twig
Labels: UI

#3879 Force default_protocol to generate an url input
  src/Wallabag/ApiBundle/Form/Type/ClientType.php
  src/Wallabag/CoreBundle/Form/Type/EditEntryType.php
  src/Wallabag/CoreBundle/Form/Type/NewEntryType.php
Labels: Ready for review

#3882 Fix CORS for API
  app/config/config.yml
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  src/Wallabag/CoreBundle/Helper/PreparePagerForEntries.php
  src/Wallabag/CoreBundle/Repository/SiteCredentialRepository.php
  src/Wallabag/ImportBundle/Import/BrowserImport.php
  src/Wallabag/ImportBundle/Import/ChromeImport.php
  src/Wallabag/ImportBundle/Import/FirefoxImport.php
  src/Wallabag/ImportBundle/Import/WallabagImport.php
  src/Wallabag/ImportBundle/Import/WallabagV1Import.php
Labels: Ready for review

#3887 Add support of expect parameter to change return object when deleting entry
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
Labels: API, Improvement

#3886 epub export: fix missing cover image, only for exports of one article
  src/Wallabag/CoreBundle/Helper/EntriesExport.php
Labels: Ready for review

#3857 Replace continue; with break; to avoid PHP 7.3 warnings
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  src/Wallabag/ImportBundle/Import/BrowserImport.php
  src/Wallabag/ImportBundle/Import/ChromeImport.php
  src/Wallabag/ImportBundle/Import/FirefoxImport.php
  src/Wallabag/ImportBundle/Import/WallabagImport.php
  src/Wallabag/ImportBundle/Import/WallabagV1Import.php
  tests/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilderTest.php
Labels: Ready for review
