Repository wallabag/wallabag, pull requests merged in 2019-10, with the labels that each got.

#4139 Update spanish translations
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.es.yml
Labels: Translations

#4147 Create code of conduct
  CODE_OF_CONDUCT.md
Labels: Meta

#4141 Updating portuguese translations
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.pt.yml
Labels: Translations

#4149 🐛 — Fix duplicated icons on "Search engine" and "new link" forms
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/new_form.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/search_form.html.twig
Labels: Ready for review, UI

#4159 Fix tests & update deps
  composer.lock
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
Labels: Ready for review
