Repository wallabag/wallabag, pull requests merged in 2020-01, with the labels that each got.

#4250 Fixed URL to share entry via twitter
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Labels: Ready for review

#4249 Ensure ENV is well defined when using make
  GNUmakefile
Labels: Ready for review

#4255 Feat/actions from sticky btn
  app/Resources/static/themes/material/css/article.scss
  app/Resources/static/themes/material/css/nav.scss
  app/Resources/static/themes/material/index.js
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
  web/wallassets/material.css
  web/wallassets/material.js
Labels: Ready for review, UI

#4263 Fix print of long pages
  app/Resources/static/themes/baggy/css/media_queries.scss
  app/Resources/static/themes/material/css/media_queries.scss
  web/wallassets/baggy.css
  web/wallassets/material.css
Labels: Ready for review, UI

#4257 Use lang attribute
  src/Wallabag/CoreBundle/Entity/Entry.php
  src/Wallabag/CoreBundle/Resources/views/base.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
  tests/Wallabag/CoreBundle/Entity/EntryTest.php
Labels: Ready for review

#4264 cosmetic changes
  app/config/config_dev.yml
  app/config/wallabag.yml
  docker-compose.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
Labels: Ready for review, Translations
