Repository wallabag/wallabag, pull requests merged in 2020-04, with the labels that each got.

#4316 Fixed bug when we delete entry via API
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
Labels: Ready for review

#4317 Enhanced article display
  app/Resources/static/themes/material/css/article.scss
  web/wallassets/baggy.js
  web/wallassets/material.css
  web/wallassets/material.js
Labels: Improvement, Ready for review, UI

#4315 Added publication date on epub export
  src/Wallabag/CoreBundle/Helper/EntriesExport.php
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
Labels: Improvement, Ready for review, export: epub

#4318 Changed authentication order in GrabySiteConfigBuilder
  src/Wallabag/CoreBundle/GuzzleSiteAuthenticator/GrabySiteConfigBuilder.php
Labels: Bug, Ready for review

#4319 Add ability to define lifetime token for the API
  app/config/config.yml
  app/config/parameters.yml.dist
Labels: Ready for review

#4325 Added authentication during import command for paywalled websites
  src/Wallabag/ImportBundle/Command/ImportCommand.php
Labels: Bug, Ready for review

#4329 Added a button to disable 2FA when enabled
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
Labels: Ready for review

#4136 Improved tags list
  app/Resources/static/themes/material/css/cards.scss
  app/Resources/static/themes/material/css/media_queries.scss
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/views/themes/material/Tag/tags.html.twig
  web/wallassets/material.css
Labels: Ready for review

#4310 TagController: fix duplicated tags when renaming them
  src/Wallabag/CoreBundle/Controller/TagController.php
  tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
Labels: Ready for review

#4346 🎨 Added more coherence with color links for material theme
  app/Resources/static/themes/material/css/article.scss
  app/Resources/static/themes/material/css/layout.scss
  app/Resources/static/themes/material/css/variables.scss
  web/wallassets/material.css
Labels: Ready for review

#4347 🎨 Changed visibility for article stats
  app/Resources/static/themes/material/css/article.scss
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_reading_time.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  web/wallassets/material.css
Labels: Ready for review

#4326 Added mass actions for Material design in list view
  app/Resources/static/themes/material/css/entries.scss
  app/Resources/static/themes/material/index.js
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/Card/_mass_checkbox.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  web/wallassets/material.css
  web/wallassets/material.js
Labels: Ready for review

#4026 Move Ignore Origin rules to database
  app/DoctrineMigrations/Version20190826204730.php
  app/config/security.yml
  app/config/wallabag.yml
  src/Wallabag/CoreBundle/Command/InstallCommand.php
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Controller/IgnoreOriginInstanceRuleController.php
  src/Wallabag/CoreBundle/DataFixtures/IgnoreOriginInstanceRuleFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/IgnoreOriginUserRuleFixtures.php
  src/Wallabag/CoreBundle/DependencyInjection/Configuration.php
  src/Wallabag/CoreBundle/DependencyInjection/WallabagCoreExtension.php
  src/Wallabag/CoreBundle/Entity/Config.php
  src/Wallabag/CoreBundle/Entity/IgnoreOriginInstanceRule.php
  src/Wallabag/CoreBundle/Entity/IgnoreOriginRuleInterface.php
  src/Wallabag/CoreBundle/Entity/IgnoreOriginUserRule.php
  src/Wallabag/CoreBundle/Entity/RuleInterface.php
  src/Wallabag/CoreBundle/Entity/TaggingRule.php
  src/Wallabag/CoreBundle/Form/Type/IgnoreOriginInstanceRuleType.php
  src/Wallabag/CoreBundle/Form/Type/IgnoreOriginUserRuleType.php
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
  src/Wallabag/CoreBundle/Helper/RuleBasedIgnoreOriginProcessor.php
  src/Wallabag/CoreBundle/Operator/PHP/PatternMatches.php
  src/Wallabag/CoreBundle/Repository/IgnoreOriginInstanceRuleRepository.php
  src/Wallabag/CoreBundle/Repository/IgnoreOriginUserRuleRepository.php
  src/Wallabag/CoreBundle/Resources/config/services.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/IgnoreOriginInstanceRule/edit.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/IgnoreOriginInstanceRule/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/IgnoreOriginInstanceRule/new.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/layout.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/IgnoreOriginInstanceRule/edit.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/IgnoreOriginInstanceRule/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/IgnoreOriginInstanceRule/new.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
  tests/Wallabag/CoreBundle/Command/ReloadEntryCommandTest.php
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/CoreBundle/Controller/IgnoreOriginInstanceRuleControllerTest.php
  tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
  tests/Wallabag/CoreBundle/Helper/RuleBasedIgnoreOriginProcessorTest.php
Labels: Ready for review

#4343 Enhanced navigation menu in material theme
  app/Resources/static/themes/material/css/nav.scss
  app/Resources/static/themes/material/index.js
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
  src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
  web/wallassets/material.css
  web/wallassets/material.js
Labels: Ready for review, UI

#4309 Replace wallabag's fork of tcpdf with the original one, PHP 7.4 support
  .travis.yml
  composer.json
  composer.lock
  src/Wallabag/ImportBundle/Controller/PocketController.php
Labels: Ready for review, Upstream

#4360 Added confirmation before mass deleting articles
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ro.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.th.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Labels: UI

#4358 Update messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
Labels: Translations

#4366 Update Japanese translation (messages.ja.yml)
  src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
Labels: Translations

#4363 Upgrade Piwik Twig Extension to Matomo
  app/DoctrineMigrations/Version20200428072628.php
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.da.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.de.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.en.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.es.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fa.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fr.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.it.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ja.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.oc.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pl.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.pt.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ro.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ru.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.th.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.tr.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.zh.yml
  app/config/services.yml
  app/config/wallabag.yml
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/Resources/views/base.html.twig
Labels: Ready for review
