Repository wallabag/wallabag, pull requests merged in 2020-08, with the labels that each got.

#4499 Translations update from Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.hr.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.uk.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.hr.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.ru.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.hr.yml
Labels: Translations

#4518 Add Croatian translation
  app/config/wallabag.yml
Labels: Ready for review, Translations

#4516 Update PagerFanta deps
  composer.json
  composer.lock
Labels: Ready for review

#4521 Move predis/predis to stable version
  composer.json
  composer.lock
Labels: Ready for review

#4524 Fix icons not showing aside nav forms
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/new_form.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/search_form.html.twig
Labels: Bug, Ready for review, UI

#4531 Update annotator to fix clean-css security
  package.json
  yarn.lock
Labels: Ready for review

#4541 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
Labels: Translations
