Repository wallabag/wallabag, pull requests merged in 2020-07, with the labels that each got.

#4464 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
Labels: Translations

#4463 Update deps
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/Repository/TagRepository.php
  src/Wallabag/CoreBundle/Twig/WallabagExtension.php
Labels: Ready for review

#4471 material: restore missing export and filter buttons on tags view
  src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
Labels: Bug, UI

#4472 Reduce opacity of archived entries on tag view
  app/Resources/static/themes/material/css/cards.scss
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_full_image.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Labels: UI

#4483 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
Labels: Translations

#4489 Add Ukrainian translation
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.uk.yml
  app/config/wallabag.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.uk.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.uk.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.uk.yml
Labels: Translations

#4494 Update deps
  composer.lock
Labels: Ready for review
