Repository wallabag/wallabag, pull requests merged in 2020-12, with the labels that each got.

#4775 Padding bottom added to article content on mobile
  app/Resources/static/themes/material/css/media_queries.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#4776 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.nb.yml
Labels: Translations

#4780 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
Labels: Translations

#4785 Translations update from Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.it.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ja.yml
Labels: Translations

#4794 Update dependabot.yml
  .github/dependabot.yml
Labels: Ready for review

#4808 Update release process and introduce 2.4.1-dev
  RELEASE_PROCESS.md
  app/config/wallabag.yml
Labels: Ready for review

#4817 Remove community.wallabag.org from the issue template
  .github/ISSUE_TEMPLATE.md
Labels: Meta

#4823 Fix missing apple-touch-icon-512.png from manifest.json
  web/img/appicon/apple-touch-icon-512.png
Labels: UI

#4822 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.oc.yml
Labels: Translations

#4833 Fix dark theme table odd style
  app/Resources/static/themes/material/css/dark_theme.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#4841 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.nl.yml
Labels: Translations

#4832 migrations: fix mysql migration for an edge case
  app/DoctrineMigrations/Version20190510141130.php
Labels: Upgrade

#4843 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1-fetching-content.md
  .github/ISSUE_TEMPLATE/2-bug-report.md
  .github/ISSUE_TEMPLATE/3-feature-request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: Meta

#4844 Add a command to clean downloaded images
  phpstan.neon
  src/Wallabag/CoreBundle/Command/CleanDownloadedImagesCommand.php
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
Labels: Ready for review

#4869 Fix extra padding on the homepage main content
  app/Resources/static/themes/material/css/media_queries.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#4865 Added a query to parse only non-hashed URL
  src/Wallabag/CoreBundle/Command/GenerateUrlHashesCommand.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
Labels: Ready for review

#4868 Show OTP secret next to the QR Code
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/material/Config/otp_app.html.twig
Labels: Improvement, Ready for review

#4894 views: add title to tag li elements, for consistency
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_full_image.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_tags.html.twig
Labels: Improvement, Ready for review, UI

#4896 Allow GitHub Actions to run on 2.* branches
  .github/workflows/assets.yml
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/translations.yml
Labels: Ready for review
