Repository wallabag/wallabag, pull requests merged in 2021-01, with the labels that each got.

#4301 Add label and issuer to otp config
  app/config/config.yml
  app/config/parameters.yml.dist
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Config/otp_app.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Config/otp_app.html.twig
Labels: Improvement, Ready for review

#4878 Fixed query to fetch URL to hash
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
Labels: Ready for review

#4900 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.da.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.nb.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.nl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.en.yml
Labels: Translations

#4904 Prepare 2.4.1
  CHANGELOG.md
  app/config/wallabag.yml
  composer.lock
Labels: Ready for review

#4908 Fix nav lang filter
  app/Resources/static/themes/material/css/nav.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#4911 Translations update from Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.ar.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ar.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.oc.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.ar.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.de.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.ar.yml
Labels: Translations

#4371 Display articles from the same domain name
  app/Resources/static/themes/material/css/cards.scss
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Controller/ExportController.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/_title.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_actions.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: Ready for review

#4883 Add a new config "use_source" to handle new ATOM format
  app/DoctrineMigrations/Version20201223222955.php
  src/Wallabag/CoreBundle/Controller/FeedController.php
  src/Wallabag/CoreBundle/Entity/Config.php
  src/Wallabag/CoreBundle/Form/Type/FeedType.php
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/entries.xml.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Config/index.html.twig
  tests/Wallabag/CoreBundle/Controller/FeedControllerTest.php
Labels: Ready for review

#4920 Translations update from Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.gl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.gl.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.gl.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.gl.yml
Labels: Translations

#4928 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.gl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.hr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.pl.yml
Labels: Translations

#4937 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
Labels: Translations

#4947 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.gl.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.gl.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.gl.yml
Labels: Translations

#4970 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.hr.yml
Labels: Translations

#4972 Preselect currently active section in the filter menu
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
Labels: Improvement, Ready for review

#4971 Fix translation of date in the footer using IntlDateFormatter
  src/Wallabag/CoreBundle/Twig/WallabagExtension.php
Labels: Ready for review

#4921 Update dark theme
  app/Resources/static/themes/material/css/dark_theme.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: Ready for review, UI

#4984 Translations update from Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.de.yml
Labels: Translations

#4983 Dark theme updated
  app/Resources/static/themes/material/css/dark_theme.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI
