Repository wallabag/wallabag, pull requests merged in 2022-02, with the labels that each got.

#5599 Add support for RTL content
  app/Resources/static/themes/baggy/css/main.css
  src/Wallabag/CoreBundle/Resources/views/base.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Labels: UI

#5594 Avoid overlapping images when downloading them
  composer.json
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
Labels: Ready for review

#5619 2.4.3
  .github/release.yml
  CHANGELOG.md
  app/config/wallabag.yml
  composer.lock
  package.json
  yarn.lock
Labels: Ready for review

#5622 Translations update from Hosted Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.pt.yml
Labels: Translations
