Repository wallabag/wallabag, pull requests merged in 2022-05, with the labels that each got.

#5742 Deprecated Baggy
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Form/Type/ConfigType.php
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/layout.html.twig
Labels: Ready for review

#5783 Translations update from Hosted Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.gl.yml
Labels: Translations

#5673 Add new endpoint for API: config
  src/Wallabag/ApiBundle/Controller/ConfigRestController.php
  src/Wallabag/ApiBundle/Resources/config/routing_rest.yml
  src/Wallabag/CoreBundle/Entity/Config.php
  tests/Wallabag/ApiBundle/Controller/ConfigRestControllerTest.php
Labels: Ready for review, API

#5381 Add action to assign a search as a tag to each result
  src/Wallabag/CoreBundle/Controller/TagController.php
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
  tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
Labels: Ready for review

#5772 Fix PHP Docker image
  docker/php/Dockerfile
Labels: Ready for review

#5792 Translations update from Hosted Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
Labels: Translations

#5775 Deprecate mobi export
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.en.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.fr.yml
  app/config/wallabag.yml
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/baggy/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Labels: export

#5794 Merge branch 2.5.0 in master
  app/Resources/static/themes/material/css/cards.scss
  app/config/config.yml
  app/config/security.yml
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Controller/ExportController.php
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/_title.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_actions.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
  src/Wallabag/CoreBundle/Twig/WallabagExtension.php
  src/Wallabag/ImportBundle/Command/ImportCommand.php
  src/Wallabag/ImportBundle/Command/RedisWorkerCommand.php
  src/Wallabag/ImportBundle/Controller/DeliciousController.php
  src/Wallabag/ImportBundle/Controller/ImportController.php
  src/Wallabag/ImportBundle/Import/DeliciousImport.php
  src/Wallabag/ImportBundle/Resources/config/rabbit.yml
  src/Wallabag/ImportBundle/Resources/config/redis.yml
  src/Wallabag/ImportBundle/Resources/config/services.yml
  src/Wallabag/ImportBundle/Resources/views/Delicious/index.html.twig
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/ImportBundle/Controller/DeliciousControllerTest.php
  tests/Wallabag/ImportBundle/Controller/ImportControllerTest.php
  tests/Wallabag/ImportBundle/fixtures/delicious_export.2021.02.06_21.10.json
  tests/Wallabag/ImportBundle/fixtures/elcurator.json
  tests/Wallabag/ImportBundle/fixtures/firefox-bookmarks.json
  tests/Wallabag/ImportBundle/fixtures/pinboard_export
  tests/Wallabag/ImportBundle/fixtures/readability-read.json
  tests/Wallabag/ImportBundle/fixtures/readability.json
  tests/Wallabag/ImportBundle/fixtures/wallabag-v1-read.json
  tests/Wallabag/ImportBundle/fixtures/wallabag-v1.json
  tests/Wallabag/ImportBundle/fixtures/wallabag-v2-read.json
  tests/Wallabag/ImportBundle/fixtures/wallabag-v2.json
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: Ready for review

#5795 Translations update from Hosted Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.zh.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
Labels: Translations

#5800 Translations update from Hosted Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.gl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.gl.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.id.yml
Labels: Translations

#5799 Prepare 2.5.0 release
  CHANGELOG.md
  app/config/wallabag.yml
  composer.lock
Labels: Ready for review

#5761 Remove SensioDistributionBundle
  .gitignore
  app/AppKernel.php
  bin/symfony_requirements
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/Resources/views/themes/common/Static/about.html.twig
  var/SymfonyRequirements.php
Labels: Ready for review

#5822 Jump to Node 16 to build assets
  .github/workflows/assets.yml
  .nvmrc
  .scrutinizer.yml
  package.json
Labels: Ready for review

#5833 Fix error about template not found in 2fa form
  src/Wallabag/UserBundle/Resources/views/Authentication/form.html.twig
Labels: Ready for review
