Repository wallabag/wallabag, pull requests merged in 2022-12, with the labels that each got.

#6125 Translations update from Hosted Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
Labels: Translations

#6136 Update to FOSUserBundle 3.1
  .github/dependabot.yml
  app/config/config.yml
  app/config/security.yml
  composer.json
  composer.lock
  phpstan-baseline.neon
  src/Wallabag/AnnotationBundle/DependencyInjection/Configuration.php
  src/Wallabag/ApiBundle/Controller/UserRestController.php
  src/Wallabag/ApiBundle/DependencyInjection/Configuration.php
  src/Wallabag/CoreBundle/Command/InstallCommand.php
  src/Wallabag/CoreBundle/DependencyInjection/Configuration.php
  src/Wallabag/CoreBundle/Event/Subscriber/SQLiteCascadeDeleteSubscriber.php
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  src/Wallabag/CoreBundle/ParamConverter/UsernameFeedTokenConverter.php
  src/Wallabag/ImportBundle/DependencyInjection/Configuration.php
  src/Wallabag/UserBundle/Controller/ManageController.php
  src/Wallabag/UserBundle/DependencyInjection/Configuration.php
  src/Wallabag/UserBundle/Entity/User.php
  templates/bundles/CraueConfigBundle/Settings/modify.html.twig
  templates/bundles/FOSUserBundle/ChangePassword/changePassword_content.html.twig
  templates/bundles/FOSUserBundle/Registration/check_email.html.twig
  templates/bundles/FOSUserBundle/Registration/confirmed.html.twig
  templates/bundles/FOSUserBundle/Registration/register_content.html.twig
  templates/bundles/FOSUserBundle/Resetting/check_email.html.twig
  templates/bundles/FOSUserBundle/Resetting/request_content.html.twig
  templates/bundles/FOSUserBundle/Resetting/reset_content.html.twig
  templates/bundles/FOSUserBundle/Security/login.html.twig
  templates/bundles/FOSUserBundle/layout.html.twig
  tests/Wallabag/CoreBundle/ParamConverter/UsernameFeedTokenConverterTest.php
Labels: Ready for review

#6144 Update to `scheb/2fa-bundle`
  composer.json
  composer.lock
Labels: Ready for review

#6154 Fix EventDispatcher & events
  phpstan-baseline.neon
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/ApiBundle/Controller/UserRestController.php
  src/Wallabag/CoreBundle/Command/InstallCommand.php
  src/Wallabag/CoreBundle/Command/ReloadEntryCommand.php
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Event/EntryDeletedEvent.php
  src/Wallabag/CoreBundle/Event/EntrySavedEvent.php
  src/Wallabag/ImportBundle/Consumer/AbstractConsumer.php
  src/Wallabag/ImportBundle/Import/AbstractImport.php
  src/Wallabag/ImportBundle/Import/BrowserImport.php
  src/Wallabag/UserBundle/Controller/ManageController.php
  tests/Wallabag/CoreBundle/Event/Listener/LocaleListenerTest.php
  tests/Wallabag/UserBundle/EventListener/AuthenticationFailureListenerTest.php
  tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
Labels: Ready for review

#6150 Replace SwiftMailer by Symfony Mailer
  app/AppKernel.php
  app/config/config.yml
  app/config/config_dev.yml
  app/config/config_test.yml
  app/config/parameters.yml.dist
  app/config/services.yml
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/Resources/views/Static/about.html.twig
  src/Wallabag/UserBundle/Mailer/AuthCodeMailer.php
  src/Wallabag/UserBundle/Mailer/UserMailer.php
  tests/Wallabag/UserBundle/Mailer/AuthCodeMailerTest.php
  tests/Wallabag/UserBundle/Mailer/CountableMemorySpool.php
Labels: Ready for review, Missing: doc

#6143 Update all Doctrine deps
  .github/dependabot.yml
  app/DoctrineMigrations/Version20160401000000.php
  app/DoctrineMigrations/Version20160410190541.php
  app/DoctrineMigrations/Version20160812120952.php
  app/DoctrineMigrations/Version20160911214952.php
  app/DoctrineMigrations/Version20160916201049.php
  app/DoctrineMigrations/Version20161001072726.php
  app/DoctrineMigrations/Version20161022134138.php
  app/DoctrineMigrations/Version20161024212538.php
  app/DoctrineMigrations/Version20161031132655.php
  app/DoctrineMigrations/Version20161104073720.php
  app/DoctrineMigrations/Version20161106113822.php
  app/DoctrineMigrations/Version20161117071626.php
  app/DoctrineMigrations/Version20161118134328.php
  app/DoctrineMigrations/Version20161122144743.php
  app/DoctrineMigrations/Version20161122203647.php
  app/DoctrineMigrations/Version20161128084725.php
  app/DoctrineMigrations/Version20161128131503.php
  app/DoctrineMigrations/Version20161214094402.php
  app/DoctrineMigrations/Version20161214094403.php
  app/DoctrineMigrations/Version20170127093841.php
  app/DoctrineMigrations/Version20170327194233.php
  app/DoctrineMigrations/Version20170405182620.php
  app/DoctrineMigrations/Version20170407200919.php
  app/DoctrineMigrations/Version20170420134133.php
  app/DoctrineMigrations/Version20170501115751.php
  app/DoctrineMigrations/Version20170510082609.php
  app/DoctrineMigrations/Version20170511115400.php
  app/DoctrineMigrations/Version20170511211659.php
  app/DoctrineMigrations/Version20170602075214.php
  app/DoctrineMigrations/Version20170606155640.php
  app/DoctrineMigrations/Version20170719231144.php
  app/DoctrineMigrations/Version20170824113337.php
  app/DoctrineMigrations/Version20171008195606.php
  app/DoctrineMigrations/Version20171105202000.php
  app/DoctrineMigrations/Version20171120163128.php
  app/DoctrineMigrations/Version20171125164500.php
  app/DoctrineMigrations/Version20180405182455.php
  app/DoctrineMigrations/Version20181128203230.php
  app/DoctrineMigrations/Version20181202073750.php
  app/DoctrineMigrations/Version20190129120000.php
  app/DoctrineMigrations/Version20190401105353.php
  app/DoctrineMigrations/Version20190601125843.php
  app/DoctrineMigrations/Version20190826204730.php
  app/config/config.yml
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Wallabag/CoreBundle/Command/InstallCommand.php
  src/Wallabag/CoreBundle/Doctrine/WallabagMigration.php
  src/Wallabag/UserBundle/Entity/User.php
  tests/Wallabag/CoreBundle/Command/InstallCommandTest.php
  tests/Wallabag/CoreBundle/Event/Subscriber/TablePrefixSubscriberTest.php
Labels: Ready for review

#6145 Update PagerFanta
  app/config/services.yml
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  src/Wallabag/UserBundle/Resources/views/Manage/index.html.twig
Labels: Ready for review

#6160 Translations update from Hosted Weblate
  translations/wallabag_user.da.yml
Labels: Translations

#6159 Move to controller as a service
  app/config/routing_dev.yml
  app/config/services.yml
  phpstan-baseline.neon
  src/Wallabag/AnnotationBundle/Controller/WallabagAnnotationController.php
  src/Wallabag/ApiBundle/Controller/ConfigRestController.php
  src/Wallabag/ApiBundle/Controller/DeveloperController.php
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/ApiBundle/Controller/SearchRestController.php
  src/Wallabag/ApiBundle/Controller/TagRestController.php
  src/Wallabag/ApiBundle/Controller/UserRestController.php
  src/Wallabag/ApiBundle/Controller/WallabagRestController.php
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Controller/ExportController.php
  src/Wallabag/CoreBundle/Controller/FeedController.php
  src/Wallabag/CoreBundle/Controller/IgnoreOriginInstanceRuleController.php
  src/Wallabag/CoreBundle/Controller/SiteCredentialController.php
  src/Wallabag/CoreBundle/Controller/StaticController.php
  src/Wallabag/CoreBundle/Controller/TagController.php
  src/Wallabag/CoreBundle/Helper/EntriesExport.php
  src/Wallabag/CoreBundle/ParamConverter/UsernameFeedTokenConverter.php
  src/Wallabag/CoreBundle/Twig/WallabagExtension.php
  src/Wallabag/ImportBundle/Controller/BrowserController.php
  src/Wallabag/ImportBundle/Controller/ChromeController.php
  src/Wallabag/ImportBundle/Controller/DeliciousController.php
  src/Wallabag/ImportBundle/Controller/ElcuratorController.php
  src/Wallabag/ImportBundle/Controller/FirefoxController.php
  src/Wallabag/ImportBundle/Controller/InstapaperController.php
  src/Wallabag/ImportBundle/Controller/PinboardController.php
  src/Wallabag/ImportBundle/Controller/PocketController.php
  src/Wallabag/ImportBundle/Controller/ReadabilityController.php
  src/Wallabag/ImportBundle/Controller/WallabagController.php
  src/Wallabag/ImportBundle/Controller/WallabagV1Controller.php
  src/Wallabag/ImportBundle/Controller/WallabagV2Controller.php
  src/Wallabag/UserBundle/Controller/ManageController.php
  tests/Wallabag/CoreBundle/Twig/WallabagExtensionTest.php
Labels: Ready for review

#6176 Translations update from Hosted Weblate
  translations/messages.en.yml
  translations/validators.en.yml
  translations/validators.pl.yml
Labels: Translations

#6178 Translations update from Hosted Weblate
  translations/messages.fr.yml
  translations/messages.pl.yml
Labels: Translations

#6171 Properly handle `json_array` type removal
  app/DoctrineMigrations/Version20160401000000.php
  app/DoctrineMigrations/Version20181202073750.php
  app/DoctrineMigrations/Version20221221092957.php
  app/config/config.yml
  src/Wallabag/CoreBundle/Doctrine/JsonArrayType.php
  src/Wallabag/UserBundle/Entity/User.php
Labels: Ready for review

#6185 Translations update from Hosted Weblate
  translations/messages.es.yml
  translations/messages.gl.yml
  translations/messages.hr.yml
  translations/messages.tr.yml
  translations/messages.zh.yml
  translations/validators.gl.yml
  translations/validators.zh.yml
Labels: Translations

#6195 Translations update from Hosted Weblate
  translations/messages.oc.yml
Labels: Translations
