Repository wallabag/wallabag, pull requests merged in 2022-03, with the labels that each got.

#5646 Fix tagging rule match when user has a custom reading speed
  src/Wallabag/CoreBundle/Command/TagAllCommand.php
  src/Wallabag/CoreBundle/DataFixtures/ConfigFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/TaggingRuleFixtures.php
  src/Wallabag/CoreBundle/Helper/RuleBasedTagger.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/CoreBundle/Helper/RuleBasedTaggerTest.php
Labels: Ready for review

#5656 Enabled greek translation
  app/config/wallabag.yml
Labels: Ready for review, Translations

#4341 Add route to list entries with annotations
  app/config/security.yml
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Controller/ExportController.php
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
  src/Wallabag/CoreBundle/Resources/translations/messages.en.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fa.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.fr.yml
  src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/_title.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/layout.html.twig
  src/Wallabag/CoreBundle/Twig/WallabagExtension.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/ImportBundle/Controller/DeliciousControllerTest.php
Labels: Ready for review

#5664 Feat/home entries updated
  app/Resources/static/themes/material/css/cards.scss
  app/Resources/static/themes/material/css/entries.scss
  app/Resources/static/themes/material/css/media_queries.scss
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_actions.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#5686 Fix test with `usinenouvelle.com` being flaky these times
  tests/Wallabag/ImportBundle/Controller/ChromeControllerTest.php
  tests/Wallabag/ImportBundle/fixtures/chrome-bookmarks
Labels: Ready for review

#5687 Add support to download webp image locally
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
Labels: Ready for review

#5680 Replace `iconv()` calls with Transliterator
  composer.json
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
  src/Wallabag/CoreBundle/Helper/EntriesExport.php
  tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
  var/SymfonyRequirements.php
Labels: Ready for review

#5647 Fix epub language
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/Helper/EntriesExport.php
Labels: Ready for review

#5695 material: improve mass buttons style, mostly for smartphone screens
  app/Resources/static/themes/material/css/entries.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: Improvement, UI, Ready for review
