Repository wallabag/wallabag, pull requests merged in 2022-01, with the labels that each got.

#5391 Translations update from Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.id.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.lt.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.tr.yml
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.zh.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.es.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.id.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.lt.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.ru.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.tr.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.id.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.lt.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.id.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.lt.yml
Labels: Translations

#5535 Add Czech language
  app/config/wallabag.yml
Labels: Translations

#5378 Show when articles is read
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_full_image.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_list.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/_card_preview.html.twig
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entries.html.twig
Labels: UI, Ready for review

#5380 Added random button on article view
  src/Wallabag/CoreBundle/Resources/views/themes/material/Entry/entry.html.twig
Labels: Ready for review

#5580 Translations update from Hosted Weblate
  src/Wallabag/CoreBundle/Resources/translations/messages.id.yml
  src/Wallabag/CoreBundle/Resources/translations/messages.zh.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.id.yml
Labels: Translations

#5581 Translations update from Hosted Weblate
  app/Resources/CraueConfigBundle/translations/CraueConfigBundle.id.yml
  src/Wallabag/CoreBundle/Resources/translations/validators.id.yml
  src/Wallabag/UserBundle/Resources/translations/wallabag_user.id.yml
Labels: Translations

#5585 Fixed wrong number of entries for tag feeds
  src/Wallabag/CoreBundle/Controller/FeedController.php
Labels: Improvement

#5591 Add build test on PHP 8.0 & 8.1
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/translations.yml
  phpunit.xml.dist
  src/Wallabag/CoreBundle/Doctrine/WallabagMigration.php
  src/Wallabag/CoreBundle/Entity/Entry.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
  tests/Wallabag/ImportBundle/Controller/ElcuratorControllerTest.php
  tests/Wallabag/ImportBundle/Controller/InstapaperControllerTest.php
  tests/Wallabag/ImportBundle/Controller/PinboardControllerTest.php
  tests/Wallabag/ImportBundle/Controller/ReadabilityControllerTest.php
  tests/Wallabag/ImportBundle/Controller/WallabagV1ControllerTest.php
  tests/Wallabag/ImportBundle/Controller/WallabagV2ControllerTest.php
  tests/Wallabag/UserBundle/Controller/ManageControllerTest.php
Labels: Ready for review
