Repository wallabag/wallabag, pull requests merged in 2023-05, with the labels that each got.

#6469 Enable PHP 8.2 in CI
  .github/workflows/continuous-integration.yml
Labels: Ready for review

#6495 Fix dark theme for pre HTML tags
  app/Resources/static/themes/material/css/dark_theme.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#6494 Translations update from Hosted Weblate
  translations/CraueConfigBundle.ml.yml
  translations/messages.ml.yml
  translations/validators.ml.yml
  translations/wallabag_user.ml.yml
Labels: Translations

#6512 Dark mode contrast improved
  app/Resources/static/themes/material/css/dark_theme.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#6525 Fix dark mode URL add input color
  app/Resources/static/themes/material/css/dark_theme.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI, Ready for review

#6562 Fix DownloadImages not following redirections
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
Labels: fetch/images
