Repository wallabag/wallabag, pull requests merged in 2023-06, with the labels that each got.

#6547 Feat/mass action UI
  app/Resources/static/themes/material/css/dark_theme.scss
  app/Resources/static/themes/material/css/entries.scss
  app/Resources/static/themes/material/css/icons.scss
  src/Wallabag/CoreBundle/Resources/views/Entry/Card/_mass_checkbox.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_preview.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/_feed_link.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  translations/messages.en.yml
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: Improvement, UI

#6571 Translations update from Hosted Weblate
  translations/messages.gl.yml
  translations/messages.hr.yml
  translations/messages.pl.yml
Labels: Translations

#6591 Translations update from Hosted Weblate
  translations/messages.es.yml
Labels: Translations

#6608 Translations update from Hosted Weblate
  translations/messages.fr.yml
  translations/messages.nb.yml
Labels: Translations

#6611 Translations update from Hosted Weblate
  translations/messages.fr.yml
  translations/messages.gl.yml
  translations/messages.pl.yml
Labels: Translations

#6612 Empty space on the top bar used for more add url toggle clickable target
  app/Resources/static/themes/material/css/nav.scss
  src/Wallabag/CoreBundle/Resources/views/layout.html.twig
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#6617 Added a missing translation
  translations/messages.en.yml
Labels: Ready for review, Translations

#6616 Changed default value for domain_name parameter
  app/config/parameters.yml.dist
Labels: Ready for review

#6620 Update translation key
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
Labels: Ready for review, Translations

#6613 Feat/entry info UI
  app/Resources/static/themes/material/css/article.scss
  app/Resources/static/themes/material/css/dark_theme.scss
  src/Wallabag/CoreBundle/Resources/views/Entry/_tags.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#6622 Update main contributors
  app/config/wallabag.yml
  src/Wallabag/CoreBundle/Resources/views/.DS_Store
  src/Wallabag/CoreBundle/Resources/views/Static/about.html.twig
  translations/messages.cs.yml
  translations/messages.da.yml
  translations/messages.de.yml
  translations/messages.el.yml
  translations/messages.en.yml
  translations/messages.es.yml
  translations/messages.fa.yml
  translations/messages.fr.yml
  translations/messages.gl.yml
  translations/messages.hr.yml
  translations/messages.hu.yml
  translations/messages.it.yml
  translations/messages.ja.yml
  translations/messages.ko.yml
  translations/messages.nb.yml
  translations/messages.nl.yml
  translations/messages.oc.yml
  translations/messages.pl.yml
  translations/messages.pt.yml
  translations/messages.ro.yml
  translations/messages.ru.yml
  translations/messages.th.yml
  translations/messages.tr.yml
  translations/messages.uk.yml
  translations/messages.zh.yml
Labels: Ready for review

#6623 Translations update from Hosted Weblate
  translations/messages.fr.yml
  translations/messages.pl.yml
Labels: Translations

#6609 Add new setting to show / hide articles thumbnails
  app/DoctrineMigrations/Version20230613121354.php
  app/Resources/static/themes/material/css/cards.scss
  app/config/services.yml
  app/config/wallabag.yml
  src/Wallabag/CoreBundle/DataFixtures/ConfigFixtures.php
  src/Wallabag/CoreBundle/DependencyInjection/Configuration.php
  src/Wallabag/CoreBundle/DependencyInjection/WallabagCoreExtension.php
  src/Wallabag/CoreBundle/Entity/Config.php
  src/Wallabag/CoreBundle/Form/Type/ConfigType.php
  src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_full_image.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_list.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_preview.html.twig
  src/Wallabag/UserBundle/EventListener/CreateConfigListener.php
  tests/Wallabag/ApiBundle/Controller/ConfigRestControllerTest.php
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
  tests/Wallabag/UserBundle/EventListener/CreateConfigListenerTest.php
  translations/messages.en.yml
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: Ready for review

#6625 Translations update from Hosted Weblate
  translations/messages.gl.yml
  translations/messages.oc.yml
Labels: Translations

#6634 Remove hardcoded string
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
Labels: Ready for review, Translations

#6637 Update quickstart content
  src/Wallabag/CoreBundle/Resources/views/Static/quickstart.html.twig
  translations/messages.en.yml
Labels: Ready for review

#6648 Do not autoload fixtures
  app/config/services.yml
  composer.lock
Labels: Ready for review

#6644 Add confirmation alert when deleting articles from list view
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_actions.html.twig
Labels: Ready for review

#6653 Fix table name in migration
  app/DoctrineMigrations/Version20221221092957.php
Labels: Ready for review

#6658 Translations update from Hosted Weblate
  translations/messages.gl.yml
  translations/messages.oc.yml
Labels: Translations

#6672 Fix undefined variable
  src/Wallabag/CoreBundle/Resources/views/Entry/_feed_link.html.twig
Labels: Ready for review

#6674 Translations update from Hosted Weblate
  translations/messages.hr.yml
Labels: Translations

#6102 ApiDoc: Add response description to WallabagRestController
  src/Wallabag/ApiBundle/Controller/WallabagRestController.php
  src/Wallabag/ApiBundle/Entity/ApplicationInfo.php
Labels: feat: api

#6682 Remove empty file
  src/Wallabag/CoreBundle/Resources/config/routing.yml
Labels: Ready for review
