Repository wallabag/wallabag, pull requests merged in 2023-08, with the labels that each got.

#6775 Remove external dependencies on src/Wallabag/CoreBundle/Resources/vie…
  src/Wallabag/ApiBundle/Controller/DeveloperController.php
  src/Wallabag/CoreBundle/Resources/views/Developer/howto_app.html.twig
Labels: Ready for review

#6803 Ensure the kernel is shut down before calling createClient
  tests/Wallabag/CoreBundle/WallabagCoreTestCase.php
Labels: Ready for review

#6811 Replace GetResponseEvent by RequestEvent
  src/Wallabag/CoreBundle/Event/Listener/LocaleListener.php
  tests/Wallabag/CoreBundle/Event/Listener/LocaleListenerTest.php
Labels: Ready for review

#6800 Move from transchoice to trans
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/Tag/tags.html.twig
Labels: Ready for review

#6798 Add mandatory $class parameter
  src/Wallabag/AnnotationBundle/DataFixtures/AnnotationFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/ConfigFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/EntryFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/IgnoreOriginUserRuleFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/SiteCredentialFixtures.php
  src/Wallabag/CoreBundle/DataFixtures/TaggingRuleFixtures.php
Labels: Ready for review

#6799 Identify platforms by their class
  app/DoctrineMigrations/Version20160401000000.php
  app/DoctrineMigrations/Version20160812120952.php
  app/DoctrineMigrations/Version20161001072726.php
  app/DoctrineMigrations/Version20161022134138.php
  app/DoctrineMigrations/Version20161024212538.php
  app/DoctrineMigrations/Version20161214094402.php
  app/DoctrineMigrations/Version20170501115751.php
  app/DoctrineMigrations/Version20170510082609.php
  app/DoctrineMigrations/Version20170511211659.php
  app/DoctrineMigrations/Version20170719231144.php
  app/DoctrineMigrations/Version20171008195606.php
  app/DoctrineMigrations/Version20181128203230.php
  app/DoctrineMigrations/Version20181202073750.php
  app/DoctrineMigrations/Version20190425115043.php
  app/DoctrineMigrations/Version20190510141130.php
  app/DoctrineMigrations/Version20190511165128.php
  app/DoctrineMigrations/Version20190619093534.php
  app/DoctrineMigrations/Version20190806130304.php
  app/DoctrineMigrations/Version20190808124957.php
  app/DoctrineMigrations/Version20190826204730.php
  app/DoctrineMigrations/Version20221221092957.php
  src/Wallabag/CoreBundle/Command/InstallCommand.php
  src/Wallabag/CoreBundle/Doctrine/WallabagMigration.php
Labels: Ready for review

#6797 Use Twig instead of templating
  app/config/config.yml
  src/Wallabag/CoreBundle/Controller/ExceptionController.php
  templates/bundles/TwigBundle/Exception/error.html.twig
Labels: Ready for review

#6826 Translations update from Hosted Weblate
  translations/messages.hr.yml
  translations/messages.pl.yml
Labels: Translations

#6817 Split symfony/symfony
  composer.json
  composer.lock
Labels: Ready for review

#6829 css: reduce risk of collision for #content
  app/Resources/static/themes/material/css/cards.scss
  app/Resources/static/themes/material/css/media_queries.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI, Ready for review

#6788 Add check if git is installed
  scripts/require.sh
Labels: Ready for review

#6119 Fix: Use Session instead of Referrer for Redirection
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Controller/TagController.php
  tests/Wallabag/CoreBundle/Controller/TagControllerTest.php
Labels: Ready for review, Work in progress

#6862 Prepare wallabag 2.6.3
  CHANGELOG.md
  app/config/wallabag.yml
  composer.lock
  src/Wallabag/ApiBundle/Controller/DeveloperController.php
  src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/Developer/index.html.twig
Labels: Ready for review

#6864 Fix checkboxes which were broken
  app/Resources/static/themes/material/css/various.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
  yarn.lock
Labels: Ready for review

#6655 Add command to clean pictures path when changing instance URL
  src/Wallabag/CoreBundle/Command/UpdatePicturesPathCommand.php
  tests/Wallabag/CoreBundle/Command/UpdatePicturesPathCommandTest.php
Labels: Ready for review

#6767 Remove (useless) demo mode
  app/DoctrineMigrations/Version20230728085538.php
  app/config/wallabag.yml
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
  translations/CraueConfigBundle.cs.yml
  translations/CraueConfigBundle.da.yml
  translations/CraueConfigBundle.de.yml
  translations/CraueConfigBundle.el.yml
  translations/CraueConfigBundle.en.yml
  translations/CraueConfigBundle.es.yml
  translations/CraueConfigBundle.fr.yml
  translations/CraueConfigBundle.gl.yml
  translations/CraueConfigBundle.hr.yml
  translations/CraueConfigBundle.hu.yml
  translations/CraueConfigBundle.id.yml
  translations/CraueConfigBundle.it.yml
  translations/CraueConfigBundle.ja.yml
  translations/CraueConfigBundle.ko.yml
  translations/CraueConfigBundle.nb.yml
  translations/CraueConfigBundle.nl.yml
  translations/CraueConfigBundle.oc.yml
  translations/CraueConfigBundle.pl.yml
  translations/CraueConfigBundle.pt.yml
  translations/CraueConfigBundle.ru.yml
  translations/CraueConfigBundle.th.yml
  translations/CraueConfigBundle.tr.yml
  translations/CraueConfigBundle.uk.yml
  translations/CraueConfigBundle.zh.yml
  translations/messages.cs.yml
  translations/messages.de.yml
  translations/messages.el.yml
  translations/messages.en.yml
  translations/messages.es.yml
  translations/messages.fa.yml
  translations/messages.fr.yml
  translations/messages.gl.yml
  translations/messages.hr.yml
  translations/messages.it.yml
  translations/messages.ja.yml
  translations/messages.ko.yml
  translations/messages.nb.yml
  translations/messages.nl.yml
  translations/messages.oc.yml
  translations/messages.pl.yml
  translations/messages.pt.yml
  translations/messages.ro.yml
  translations/messages.ru.yml
  translations/messages.th.yml
  translations/messages.tr.yml
  translations/messages.uk.yml
  translations/messages.zh.yml
Labels: Ready for review

#6769 Add `isNotParsed` field on Entry entity
  app/DoctrineMigrations/Version20230728093912.php
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/CoreBundle/Command/ReloadEntryCommand.php
  src/Wallabag/CoreBundle/DataFixtures/EntryFixtures.php
  src/Wallabag/CoreBundle/Entity/Entry.php
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  src/Wallabag/CoreBundle/Helper/ContentProxy.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  src/Wallabag/ImportBundle/Import/WallabagImport.php
  src/Wallabag/ImportBundle/Import/WallabagV1Import.php
  tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
  tests/Wallabag/CoreBundle/Command/ReloadEntryCommandTest.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php
  translations/messages.en.yml
Labels: Ready for review

#6793 Fix search when search term has useless space
  src/Wallabag/CoreBundle/Controller/EntryController.php
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
Labels: Ready for review

#6822 Resolve self depreciation
  src/Wallabag/CoreBundle/Command/UpdatePicturesPathCommand.php
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Controller/TagController.php
  src/Wallabag/CoreBundle/DataFixtures/EntryFixtures.php
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  src/Wallabag/CoreBundle/Twig/WallabagExtension.php
  tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
  tests/Wallabag/CoreBundle/Twig/WallabagExtensionTest.php
Labels: Ready for review

#6768 Remove mobi export
  app/DoctrineMigrations/Version20230728091417.php
  app/config/config.yml
  app/config/wallabag.yml
  composer.json
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/entry.html.twig
  src/Wallabag/CoreBundle/Resources/views/Static/about.html.twig
  translations/CraueConfigBundle.cs.yml
  translations/CraueConfigBundle.da.yml
  translations/CraueConfigBundle.de.yml
  translations/CraueConfigBundle.el.yml
  translations/CraueConfigBundle.en.yml
  translations/CraueConfigBundle.es.yml
  translations/CraueConfigBundle.fa.yml
  translations/CraueConfigBundle.fr.yml
  translations/CraueConfigBundle.gl.yml
  translations/CraueConfigBundle.hu.yml
  translations/CraueConfigBundle.id.yml
  translations/CraueConfigBundle.it.yml
  translations/CraueConfigBundle.ja.yml
  translations/CraueConfigBundle.ko.yml
  translations/CraueConfigBundle.nb.yml
  translations/CraueConfigBundle.nl.yml
  translations/CraueConfigBundle.oc.yml
  translations/CraueConfigBundle.pl.yml
  translations/CraueConfigBundle.pt.yml
  translations/CraueConfigBundle.ro.yml
  translations/CraueConfigBundle.ru.yml
  translations/CraueConfigBundle.th.yml
  translations/CraueConfigBundle.tr.yml
  translations/CraueConfigBundle.uk.yml
  translations/CraueConfigBundle.zh.yml
Labels: Ready for review

#6874 Fix #6873 override materializecss checkbox pointer-events disabled
  app/Resources/static/themes/material/css/various.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: Bug, Ready for review

#6876 Remove remaining MOBI stuff
  composer.lock
  src/Wallabag/ApiBundle/Controller/EntryRestController.php
  src/Wallabag/CoreBundle/Controller/ExportController.php
  src/Wallabag/CoreBundle/Helper/EntriesExport.php
  tests/Wallabag/ApiBundle/Controller/EntryRestControllerTest.php
  tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
Labels: Ready for review

#6791 Change public registration to false by default
  app/config/parameters.yml.dist
  app/config/parameters_test.yml
  app/config/tests/parameters_test.mysql.yml
  app/config/tests/parameters_test.pgsql.yml
  app/config/tests/parameters_test.sqlite.yml
  docker/php/config/parameters.yml
Labels: Ready for review

#6883 Translations update from Hosted Weblate
  translations/messages.es.yml
  translations/messages.gl.yml
  translations/messages.pl.yml
Labels: Translations

#6889 Translations update from Hosted Weblate
  translations/messages.fr.yml
  translations/messages.hr.yml
  translations/messages.it.yml
  translations/messages.oc.yml
  translations/messages.tr.yml
Labels: Translations

#6888 Feat/domain status filters html types
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
Labels: UI

#6896 Prepare wallabag 2.6.5
  CHANGELOG.md
  app/config/wallabag.yml
Labels: Ready for review

#6897 Fix checkboxes pointer events issue
  app/Resources/static/themes/material/css/various.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#6899 Add Google mailer
  .github/workflows/assets.yml
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/translations.yml
  composer.json
  composer.lock
Labels: Ready for review
