Repository wallabag/wallabag, pull requests merged in 2023-12, with the labels that each got.

#7109 Translations update from Hosted Weblate
  translations/messages.gl.yml
Labels: Translations

#7133 Fix/dark mode disabled url 2.6
  app/Resources/static/themes/material/css/dark_theme.scss
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#7135 Use wallabag rulerz packages
  app/config/config.yml
  composer.json
  composer.lock
Labels: Meta

#7144 Use Node 20
  .nvmrc
  composer.lock
  docker/php/Dockerfile
  package.json
  yarn.lock
Labels: Ready for review
