Repository wallabag/wallabag, pull requests merged in 2023-09, with the labels that each got.

#6912 Mass action layout improved
  app/Resources/static/themes/material/css/entries.scss
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#6923 Translations update from Hosted Weblate
  translations/messages.es.yml
Labels: Translations

#6924 Force secure cookie on HTTPS connection
  app/config/config.yml
Labels: Security, Ready for review

#6926 Prepare 2.6.6 release
  CHANGELOG.md
  app/config/wallabag.yml
  composer.lock
Labels: Ready for review

#6942 Move grouping deps in the right place
  .github/dependabot.yml
Labels: Ready for review, Meta

#6955 Remove unused font `ptsans-npm-webfont`
  package.json
  yarn.lock
Labels: Improvement, javascript

#6953 Upgrade to NodeJS 18
  .github/workflows/assets.yml
  .nvmrc
  package.json
Labels: Improvement, javascript

#6965 Port 2.6 branch to master
  .github/workflows/assets.yml
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/translations.yml
  CHANGELOG.md
  app/Resources/static/themes/material/css/entries.scss
  app/Resources/static/themes/material/css/nav.scss
  app/Resources/static/themes/material/css/various.scss
  app/config/config.yml
  app/config/wallabag.yml
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/Controller/EntryController.php
  src/Wallabag/CoreBundle/Form/Type/EntryFilterType.php
  src/Wallabag/CoreBundle/Repository/EntryRepository.php
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  src/Wallabag/CoreBundle/Resources/views/layout.html.twig
  src/Wallabag/CoreBundle/Twig/WallabagExtension.php
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: Ready for review

#6968 Translations update from Hosted Weblate
  translations/messages.cs.yml
Labels: Translations

#6991 Fix #6971 - Full clickable card on mass action
  app/Resources/static/themes/material/css/entries.scss
  src/Wallabag/CoreBundle/Resources/views/Entry/Card/_mass_checkbox.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_preview.html.twig
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI

#6986 Add tag form submit button always displayed
  app/Resources/static/themes/material/css/article.scss
  src/Wallabag/CoreBundle/Resources/views/Tag/new_form.html.twig
  web/wallassets/material.css
  web/wallassets/material.css.map
Labels: UI
