Repository wallabag/wallabag, pull requests merged in 2023-07, with the labels that each got.

#6678 Skip migration if the table was already renamed
  app/DoctrineMigrations/Version20170606155640.php
Labels: topic: migration

#6680 Fix export for same domain entries
  src/Wallabag/CoreBundle/Controller/ExportController.php
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  tests/Wallabag/CoreBundle/Controller/ExportControllerTest.php
Labels: Ready for review

#6684 ApiDoc: Add response description to UserRestController
  src/Wallabag/ApiBundle/Controller/UserRestController.php
  src/Wallabag/ApiBundle/Entity/Client.php
  src/Wallabag/UserBundle/Entity/User.php
Labels: Documentation

#6685 Document how to run tests and formatter for new contributors
  .github/CONTRIBUTING.md
Labels: Documentation, Work in progress

#6723 Remove `twofactor_auth` parameter
  app/config/config.yml
  app/config/parameters.yml.dist
  docker/php/config/parameters.yml
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
  src/Wallabag/UserBundle/Controller/ManageController.php
  src/Wallabag/UserBundle/Resources/views/Manage/edit.html.twig
  tests/Wallabag/CoreBundle/Controller/SecurityControllerTest.php
Labels: Ready for review

#6744 Translations update from Hosted Weblate
  translations/messages.fr.yml
Labels: Translations

#6738 Prepare 2.6.2 release
  CHANGELOG.md
  app/config/wallabag.yml
  composer.lock
Labels: Ready for review

#6754 Update RELEASE_PROCESS
  RELEASE_PROCESS.md
Labels: Ready for review

#6762 Add composer normalizer
  .github/workflows/coding-standards.yml
  composer.json
  composer.lock
Labels: Ready for review
