Repository wallabag/wallabag, pull requests merged in 2023-10, with the labels that each got.

#7002 Updated text iTunes to App Store.
  app/config/parameters_addons.yml
  translations/messages.cs.yml
  translations/messages.de.yml
  translations/messages.el.yml
  translations/messages.en.yml
  translations/messages.es.yml
  translations/messages.fa.yml
  translations/messages.fr.yml
  translations/messages.gl.yml
  translations/messages.hr.yml
  translations/messages.hu.yml
  translations/messages.it.yml
  translations/messages.ja.yml
  translations/messages.nb.yml
  translations/messages.nl.yml
  translations/messages.oc.yml
  translations/messages.pl.yml
  translations/messages.pt.yml
  translations/messages.ro.yml
  translations/messages.ru.yml
  translations/messages.th.yml
  translations/messages.tr.yml
  translations/messages.uk.yml
Labels: Translations

#7003 Avoid deps for Symfony/*
  .github/dependabot.yml
Labels: Ready for review, dependencies

#7005 Fix symfony pattern for dependabot
  .github/dependabot.yml
Labels: Ready for review, dependencies

#7006 Prepare 2.6.7 release
  CHANGELOG.md
  app/config/wallabag.yml
  composer.lock
  phpstan-baseline.neon
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Form/Type/UserInformationType.php
  src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
Labels: Ready for review

#7012 Corrected PL translations
  translations/CraueConfigBundle.pl.yml
Labels: Translations

#7039 Backport 2.6.7
  CHANGELOG.md
  app/Resources/static/themes/material/css/article.scss
  app/Resources/static/themes/material/css/entries.scss
  app/config/wallabag.yml
  composer.lock
  phpstan-baseline.neon
  phpstan.neon
  src/Wallabag/CoreBundle/Controller/ConfigController.php
  src/Wallabag/CoreBundle/Form/Type/UserInformationType.php
  src/Wallabag/CoreBundle/Resources/views/Config/index.html.twig
  src/Wallabag/CoreBundle/Resources/views/Config/otp_app.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/Card/_mass_checkbox.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_preview.html.twig
  src/Wallabag/CoreBundle/Resources/views/Tag/new_form.html.twig
  tests/Wallabag/CoreBundle/Controller/ConfigControllerTest.php
Labels: Ready for review
