Repository wallabag/wallabag, pull requests merged in 2024-02, with the labels that each got.

#7231 Configure MakerBundle
  app/config/config.yml
Labels: Ready for review

#7229 Integrate bdunogier/guzzle-site-authenticator in core
  app/AppKernel.php
  app/config/services.yml
  composer.json
  composer.lock
  src/Wallabag/CoreBundle/ExpressionLanguage/AuthenticatorProvider.php
  src/Wallabag/CoreBundle/Guzzle/AuthenticatorSubscriber.php
  src/Wallabag/CoreBundle/Guzzle/FixupMondeDiplomatiqueUriSubscriber.php
  src/Wallabag/CoreBundle/SiteConfig/ArraySiteConfigBuilder.php
  src/Wallabag/CoreBundle/SiteConfig/Authenticator/Authenticator.php
  src/Wallabag/CoreBundle/SiteConfig/Authenticator/Factory.php
  src/Wallabag/CoreBundle/SiteConfig/Authenticator/LoginFormAuthenticator.php
  src/Wallabag/CoreBundle/SiteConfig/GrabySiteConfigBuilder.php
  src/Wallabag/CoreBundle/SiteConfig/SiteConfig.php
  src/Wallabag/CoreBundle/SiteConfig/SiteConfigBuilder.php
  tests/Wallabag/CoreBundle/Guzzle/AuthenticatorSubscriberTest.php
  tests/Wallabag/CoreBundle/Guzzle/FixupMondeDiplomatiqueUriSubscriberTest.php
  tests/Wallabag/CoreBundle/SiteConfig/ArraySiteConfigBuilderTest.php
  tests/Wallabag/CoreBundle/SiteConfig/Authenticator/LoginFormAuthenticatorTest.php
  tests/Wallabag/CoreBundle/SiteConfig/GrabySiteConfigBuilderTest.php
  tests/Wallabag/CoreBundle/SiteConfig/SiteConfigTest.php
  tests/Wallabag/CoreBundle/fixtures/aoc.media.html
  tests/Wallabag/CoreBundle/fixtures/nextinpact-article.html
  tests/Wallabag/CoreBundle/fixtures/nextinpact-login.html
Labels: Ready for review

#7244 Translations update from Hosted Weblate
  translations/messages.ar.yml
Labels: Translations

#7247 Make DownloadImages use HttpClient
  app/config/config.yml
  app/config/services.yml
  src/Wallabag/CoreBundle/Helper/DownloadImages.php
  tests/Wallabag/CoreBundle/Helper/DownloadImagesTest.php
Labels: Ready for review

#7266 Fix same domain pagination
  src/Wallabag/CoreBundle/Controller/EntryController.php
Labels: Ready for review

#7265 Make retries an instance property in AuthenticatorSubscriber
  src/Wallabag/CoreBundle/Guzzle/AuthenticatorSubscriber.php
Labels: Ready for review

#7272 Upgrade PHP dependencies
  composer.json
  composer.lock
Labels: Ready for review, dependencies

#7267 Make migrations noop instead of skipping
  app/DoctrineMigrations/Version20161001072726.php
  app/DoctrineMigrations/Version20161022134138.php
  app/DoctrineMigrations/Version20170510082609.php
  app/DoctrineMigrations/Version20170719231144.php
  app/DoctrineMigrations/Version20171008195606.php
  app/DoctrineMigrations/Version20181128203230.php
  app/DoctrineMigrations/Version20190511165128.php
  app/DoctrineMigrations/Version20190619093534.php
Labels: Ready for review

#7248 Make PocketImport use HttpClient
  app/config/config.yml
  app/config/services.yml
  src/Wallabag/CoreBundle/Import/PocketImport.php
  tests/Wallabag/CoreBundle/Import/PocketImportTest.php
Labels: Ready for review

#7273 Translations update from Hosted Weblate
  translations/CraueConfigBundle.zh_Hant.yml
  translations/messages.zh_Hant.yml
Labels: Translations

#7275 Translations update from Hosted Weblate
  translations/CraueConfigBundle.zh_Hant.yml
  translations/messages.zh_Hant.yml
  translations/validators.zh_Hant.yml
Labels: Translations

#7287 Update composer.json
  composer.json
  composer.lock
Labels: Ready for review

#7290 Use lighter PDF file in Pinboard tests
  tests/Controller/Import/PinboardControllerTest.php
  tests/fixtures/Import/pinboard_export
Labels: Ready for review

#7292 Rename WallabagCoreTestCase to WallabagTestCase
  tests/Command/CleanDuplicatesCommandTest.php
  tests/Command/ExportCommandTest.php
  tests/Command/GenerateUrlHashesCommandTest.php
  tests/Command/Import/ImportCommandTest.php
  tests/Command/Import/RedisWorkerCommandTest.php
  tests/Command/InstallCommandTest.php
  tests/Command/ListUserCommandTest.php
  tests/Command/ReloadEntryCommandTest.php
  tests/Command/ShowUserCommandTest.php
  tests/Command/TagAllCommandTest.php
  tests/Command/UpdatePicturesPathCommandTest.php
  tests/Controller/AnnotationControllerTest.php
  tests/Controller/Api/DeveloperControllerTest.php
  tests/Controller/ConfigControllerTest.php
  tests/Controller/EntryControllerTest.php
  tests/Controller/ExportControllerTest.php
  tests/Controller/FeedControllerTest.php
  tests/Controller/IgnoreOriginInstanceRuleControllerTest.php
  tests/Controller/Import/ChromeControllerTest.php
  tests/Controller/Import/DeliciousControllerTest.php
  tests/Controller/Import/ElcuratorControllerTest.php
  tests/Controller/Import/FirefoxControllerTest.php
  tests/Controller/Import/ImportControllerTest.php
  tests/Controller/Import/InstapaperControllerTest.php
  tests/Controller/Import/PinboardControllerTest.php
  tests/Controller/Import/PocketControllerTest.php
  tests/Controller/Import/PocketHtmlControllerTest.php
  tests/Controller/Import/ReadabilityControllerTest.php
  tests/Controller/Import/ShaarliControllerTest.php
  tests/Controller/Import/WallabagV1ControllerTest.php
  tests/Controller/Import/WallabagV2ControllerTest.php
  tests/Controller/SecurityControllerTest.php
  tests/Controller/SettingsControllerTest.php
  tests/Controller/SiteCredentialControllerTest.php
  tests/Controller/StaticControllerTest.php
  tests/Controller/TagControllerTest.php
  tests/Controller/UserControllerTest.php
  tests/Entity/EntryTest.php
  tests/SiteConfig/GrabySiteConfigBuilderTest.php
  tests/WallabagTestCase.php
Labels: Ready for review

#7293 RabbitMQ env vars
  docker/php/config/parameters.yml
Labels: Ready for review

#7286 Translations update from Hosted Weblate
  translations/messages.zh_Hant.yml
  translations/validators.zh_Hant.yml
  translations/wallabag_user.zh_Hant.yml
Labels: Translations

#7294 Move assets to assets/ root folder "as is"
  .gitignore
  app/Resources/static/themes/_global/img/bg-select.png
  app/Resources/static/themes/_global/img/icons/Diaspora-asterisk.svg
  app/Resources/static/themes/_global/img/icons/diaspora-icon--white.png
  app/Resources/static/themes/_global/img/list.png
  app/Resources/static/themes/_global/img/table.png
  app/config/webpack/common.js
  app/config/webpack/prod.js
  assets/_global/global.scss
  assets/_global/img/icons/diaspora-icon--black.png
  assets/_global/img/icons/scuttle.png
  assets/_global/img/icons/shaarli.png
  assets/_global/img/icons/unmark-icon--black.png
  assets/_global/index.js
  assets/_global/js/bookmarklet.js
  assets/_global/js/highlight.js
  assets/_global/js/shortcuts/entry.js
  assets/_global/js/shortcuts/main.js
  assets/_global/js/tools.js
  assets/_global/share.js
  assets/_global/share.scss
  assets/material/css/article.scss
  assets/material/css/cards.scss
  assets/material/css/dark_theme.scss
  assets/material/css/entries.scss
  assets/material/css/filters.scss
  assets/material/css/fonts.scss
  assets/material/css/icons.scss
  assets/material/css/index.scss
  assets/material/css/layout.scss
  assets/material/css/media_queries.scss
  assets/material/css/nav.scss
  assets/material/css/print.scss
  assets/material/css/sidenav.scss
  assets/material/css/variables.scss
  assets/material/css/various.scss
  assets/material/index.js
  assets/material/js/shortcuts/entry.js
  assets/material/js/shortcuts/main.js
  assets/material/js/tools.js
  templates/Entry/entries.xml.twig
  tests/Controller/FeedControllerTest.php
Labels: Ready for review

#7288 Setup Blackfire
  .env
  .gitignore
  docker-compose.yml
  docker/php/Dockerfile
Labels: Ready for review

#7289 Run tests in no debug mode
  app/config/config.yml
  app/config/services_test.yml
  phpstan.neon
  phpunit.xml.dist
  src/Controller/Api/EntryRestController.php
  tests/Command/ReloadEntryCommandTest.php
  tests/Controller/Api/DeveloperControllerTest.php
  tests/Controller/Api/WallabagApiTestCase.php
  tests/Controller/ConfigControllerTest.php
  tests/Controller/ExportControllerTest.php
  tests/WallabagTestCase.php
  tests/bootstrap.php
Labels: Ready for review

#7302 Translations update from Hosted Weblate
  translations/messages.zh_Hant.yml
Labels: Translations
