Repository wallabag/wallabag, pull requests merged in 2024-11, with the labels that each got.

#7754 Added Omnivore Import
  app/config/config.yml
  app/config/services.yml
  app/config/services_rabbit.yml
  app/config/services_redis.yml
  src/Wallabag/ImportBundle/Command/ImportCommand.php
  src/Wallabag/ImportBundle/Command/RedisWorkerCommand.php
  src/Wallabag/ImportBundle/Consumer/RabbitMQConsumerTotalProxy.php
  src/Wallabag/ImportBundle/Controller/ImportController.php
  src/Wallabag/ImportBundle/Controller/OmnivoreController.php
  src/Wallabag/ImportBundle/Import/OmnivoreImport.php
  src/Wallabag/ImportBundle/Resources/views/Omnivore/index.html.twig
  tests/Wallabag/ImportBundle/Controller/ImportControllerTest.php
  tests/Wallabag/ImportBundle/Controller/OmnivoreControllerTest.php
  tests/Wallabag/ImportBundle/fixtures/omnivore.json
  translations/messages.en.yml
  web/wallassets/41a1d465797f51702171.otf
Labels: Ready for review

#7782 Translations update from Hosted Weblate
  translations/CraueConfigBundle.ta.yml
  translations/messages.ta.yml
  translations/validators.ta.yml
  translations/wallabag_user.ta.yml
Labels: Translations

#7799 Add Markdown export
  app/config/wallabag.yml
  composer.json
  composer.lock
  migrations/Version20241112193044.php
  src/Controller/ExportController.php
  src/Helper/EntriesExport.php
  templates/Entry/entries.html.twig
  templates/Entry/entry.html.twig
  tests/Controller/ExportControllerTest.php
Labels: Ready for review

#7803 Translations update from Hosted Weblate
  translations/CraueConfigBundle.be.yml
  translations/messages.be.yml
  translations/validators.be.yml
  translations/wallabag_user.be.yml
Labels: Translations

#7805 Improved import page
  templates/Import/index.html.twig
  tests/Controller/Import/ImportControllerTest.php
Labels: UI, Ready for review

#7768 Restored lazy connections for RabbitMQ
  .github/workflows/continuous-integration.yml
  app/config/services_rabbit.yml
Labels: Ready for review

#7807 Update Symfony components after 5.4.47 release
  composer.lock
Labels: Ready for review

#7804 Translations update from Hosted Weblate
  translations/CraueConfigBundle.be.yml
  translations/CraueConfigBundle.be_Latn.yml
  translations/messages.be.yml
  translations/messages.be_Latn.yml
  translations/validators.be_Latn.yml
  translations/wallabag_user.be.yml
  translations/wallabag_user.be_Latn.yml
Labels: Translations

#7817 Translations update from Hosted Weblate
  translations/messages.be.yml
  translations/messages.nl.yml
  translations/messages.pl.yml
Labels: Translations

#7833 Add php 8.4 for our CI
  .github/workflows/continuous-integration.yml
Labels: Ready for review

#7827 Fix redirection after action in search results
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_actions.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/_card_list.html.twig
  src/Wallabag/CoreBundle/Resources/views/Entry/entries.html.twig
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
Labels: Missing: tests

#7846 Fix title tag filter
  src/Wallabag/CoreBundle/Resources/views/Entry/_title.html.twig
Labels: UI, Ready for review
