Repository wallabag/wallabag, pull requests merged in 2024-07, with the labels that each got.

#7568 Translations update from Hosted Weblate
  translations/validators.ar.yml
  translations/wallabag_user.ar.yml
Labels: Translations

#7577 Fix tests
  composer.lock
  tests/Controller/Api/EntryRestControllerTest.php
  tests/Controller/EntryControllerTest.php
  tests/Controller/Import/FirefoxControllerTest.php
  tests/Controller/Import/PocketHtmlControllerTest.php
  tests/Controller/Import/ShaarliControllerTest.php
  tests/fixtures/Import/firefox-bookmarks.json
  tests/fixtures/Import/ril_export.html
  tests/fixtures/Import/shaarli-bookmarks.html
Labels: Ready for review

#7583 Update all deps
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Mailer/UserMailer.php
Labels: Ready for review

#7582 Update site config & tests
  composer.json
  composer.lock
  tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php
  tests/Wallabag/ImportBundle/Controller/FirefoxControllerTest.php
  tests/Wallabag/ImportBundle/fixtures/firefox-bookmarks.json
Labels: Ready for review

#7570 Feature: tagging rules reset
  src/Controller/ConfigController.php
  src/Repository/TaggingRuleRepository.php
  templates/Config/index.html.twig
  tests/Controller/ConfigControllerTest.php
  translations/messages.en.yml
  translations/messages.zh.yml
  translations/messages.zh_Hant.yml
Labels: Feature

#7586 Translations update from Hosted Weblate
  translations/messages.pl.yml
  translations/messages.tr.yml
Labels: Translations
