Repository wallabag/wallabag, pull requests merged in 2024-05, with the labels that each got.

#7464 Enable Swagger JSON output in routing.yml
  app/config/routing.yml
Labels: feat: api

#7491 Add sharing to linkding
  app/config/wallabag.yml
  assets/_global/img/icons/linkding.svg
  assets/material/css/icons.scss
  migrations/Version20240521152037.php
  templates/Entry/entry.html.twig
  translations/CraueConfigBundle.en.yml
Labels: Feature

#7510 Translations update from Hosted Weblate
  translations/messages.gl.yml
Labels: Translations
